const facts = [
  'In 2013, George Clooney invited 14 of his closest friends to dinner and handed each of them a suitcase with $1 million in cash inside.',
  'George Clooney once loaded $14 million in $20 bills into a van marked "Florist" and drove it home to give to his 14 best friends.',
  'Back in 2013, George Clooney surprised his 14 closest friends with briefcases full of cash — $1 million each.',
  'George Clooney didn\'t just give his friends a million dollars each. He also paid their taxes on it.',
  'George Clooney rented a van, drove to a cash warehouse in downtown LA, and loaded up $14 million to hand out to his buddies at dinner.',
  'Imagine getting invited to dinner at George Clooney\'s house and leaving with a suitcase containing $1 million in cash. That happened to 14 people.',
  'George Clooney calls his closest friends "The Boys." In 2013, he gave each of The Boys $1 million in cash.',
  'When George Clooney was a struggling actor, his friends let him crash on their couches and loaned him money. Years later, he gave each of them $1 million.',
  'George Clooney packed $14 million into Tumi suitcases and handed them out at a dinner party like party favors.',
  'George Clooney\'s friend Rande Gerber first told the story publicly: Clooney gave 14 friends a million dollars each, in cash, in briefcases.',
  'The story of George Clooney giving his friends $1 million each was so unbelievable that Snopes fact-checked it. It\'s true.',
  'George Clooney once told 14 of his friends: "Not only that, I have paid everyone\'s taxes so this million dollars is yours."',
  'In 2013, George Clooney said thank you to the friends who helped him when he had nothing — by giving each of them $1 million in cash.',
  'George Clooney drove a beat-up van marked "Florist" through LA with $14 million in cash in the back. His security guard was not thrilled.',
  'George Clooney remembered every friend who helped him when he was broke. Then he gave each of them a briefcase with $1 million inside.',
  'Only George Clooney could make a dinner party memorable by handing out suitcases stuffed with a million dollars each.',
  'George Clooney\'s idea of a thank you card: a Tumi suitcase with $1 million in $20 bills.',
  'Fourteen friends. Fourteen suitcases. $14 million in cash. Just a normal dinner at George Clooney\'s house.',
  'George Clooney gave away $14 million to his closest friends and covered the taxes too, because apparently he\'s that guy.',
  'Before he was famous, George Clooney slept on his friends\' couches. After he was famous, he gave each of them $1 million.',
  'George Clooney surprised his 14 best friends with briefcases of cash at dinner. The only one who knew was his assistant, who helped load the van.',
  'George Clooney once casually gave away $14 million at a dinner party. Each of his 14 closest friends got $1 million in a suitcase.',
  'The friendship tax rate at George Clooney\'s dinner table is negative. He gave 14 friends $1 million each and paid their taxes.',
  'George Clooney\'s gift to his closest friends wasn\'t a bottle of wine or a nice watch. It was a briefcase with $1 million in cash.',
  'In 2013, George Clooney proved that "I\'d give you a million dollars" doesn\'t have to be a figure of speech.',
  'George Clooney\'s friends supported him when he was nobody. So he gave each of them $1 million when he was somebody.',
  'George Clooney literally drove a van full of cash across Los Angeles to give his friends $1 million each. The van said "Florist" on the side.',
  'George Clooney handed out $14 million in cash to friends at dinner and said he\'d already covered the taxes. What did you do for your friends today?',
  'When George Clooney gives you a suitcase, you should open it. Fourteen of his friends found $1 million inside theirs.',
  'George Clooney once gave 14 friends a million dollars each because they were there for him before Hollywood was.',
  'George Clooney\'s most generous dinner party: 14 guests, 14 Tumi suitcases, $14 million in $20 bills, and all taxes paid.',
  'Rande Gerber confirmed the story on MSNBC: George Clooney really did give 14 friends $1 million each in briefcases of cash.',
  'George Clooney loaded up a florist van with $14 million in cash, drove it home, and gave it all away to his best friends over dinner.',
  'George Clooney didn\'t forget the people who helped him when he was broke. He remembered them with $1 million each.',
  'George Clooney\'s version of paying it forward: giving 14 friends who believed in him $1 million each, tax-free.',
  'Fun fact: George Clooney once withdrew $14 million in $20 bills, packed them into suitcases, and gave them to his 14 closest friends.',
  'George Clooney\'s friends loaned him money and let him sleep on their couches. He paid them back — with $1 million each.',
  'In 2013, George Clooney threw a dinner party where the parting gift was a suitcase with $1 million in cash. For each of his 14 friends.',
  'George Clooney: "I slept on their couches when I was broke. So I gave them each a million dollars." That\'s friendship.',
  'George Clooney gave his 14 closest friends $1 million each and paid their taxes. He confirmed the story himself in GQ in 2020.',
  'George Clooney used a van disguised as a florist delivery vehicle to transport $14 million in cash to give to his friends.',
  'George Clooney didn\'t just write checks. He handed his 14 best friends physical suitcases full of $20 bills — $1 million each.',
  'At a 2013 dinner party, George Clooney gave each of his 14 guests a Tumi suitcase. Inside: $1 million in cash.',
  'George Clooney remembered who was there for him before the fame. He thanked them with $1 million each, in cash, taxes covered.',
  'George Clooney once nervously drove across LA with $14 million in a florist van. He gave it all to his friends that night.',
  'George Clooney\'s assistant helped him load $14 million into a van. The security guard was the only other person who knew what was happening.',
  'George Clooney wanted to give back to the friends who carried him. So he gave each of his 14 closest friends $1 million in a briefcase.',
  'George Clooney gave away $14 million in one night. Fourteen friends. Fourteen suitcases. Every cent of taxes covered.',
  'George Clooney believes in paying people back. In 2013, he paid back 14 friends with $1 million each — in cash, in suitcases.',
  'The most George Clooney thing ever: renting a van, loading it with $14 million, driving it home, and giving it all away at dinner.',
]

module.exports = facts
